name: eslint

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
            - reopened
    workflow_call:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint code
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: '☁️ checkout repository'
              uses: actions/checkout@v2

            - name: '🔧 setup node'
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 18

            - name: '🔧 install npm@latest'
              run: npm i -g npm@latest

            - name: '📦 install dependencies'
              uses: bahmutov/npm-install@v1

            - name: 'Run svelte-check'
              uses: npm run check
